global:
    scrape_interval: 5s
scrape_configs:
    - job_name: 'flowise-app'
      metrics_path: '/api/v1/metrics'
      static_configs:
          - targets: [ 'host.docker.internal:3000' ]

    - job_name: 'otel-collector'
      metrics_path: '/metrics'
      static_configs:
          - targets: [ 'host.docker.internal:8889' ]